### ISSUE TITLE
npm script

### ISSUE THREAD

**Issue by fridaystreet** [nneves/openwrt_mips_ar9331_nodejs#2]
HI,

thanks for all your efforts on this I've just run the node script and it's completed and compiled node for me. It took a few hours, but that's a small price to pay. So I wanted to compile a module and looked to use your npm script, however I can't seem to get it to work. I think it's probably something I'm doing wrong possibly. If I try running it I just get the error:

"./npm_mips_ar9331.sh: line 23: npm: command not found" 

I had a look at the script and it doesn't look like it's referencing the path to npm anywhere. So I tried putting a path in front of npm in the script:

"node-v0.10-5-mips/deps/npm/bin/npm"

Which seems to be now running npm ok, but I'm now getting this error:

"node-v0.10-5-mips/deps/npm/bin/npm: 12: node-v0.10-5-mips/deps/npm/bin/npm: node: not found"

Are you able to shed any light on where I'm going wrong please?

Cheers
Paul

**Comment by fridaystreet** [comment]
apologies I hadn't checked the closed issues doh! Looks like I'm missing the bit where I need to install node locally. I thought for some reason it meant it uses the version of npm in the openwrt source stuff.

All good thanks

**Comment by nneves** [comment]
I haven't completed the all instructions for the ./npm_mips_ar9331.sh script, it's not a perfect solution and would like to get something better, but for now it's working! Glad to see that you have sorted this out, take extra attention to the special flags when launching node to avoid using excessive resources!

**Comment by fridaystreet** [comment]
@nneves it's miles ahead of anything else out there so give yourself a pat on the back :-) Thanks for the tip. 

One question I did have in relation to the size of the compiled files. I originally downloaded the compiled files form giorgiocefaro that you also reference in your posts. His node file is only 1.6mb and he has another small library of 64k. I was just wondering what the difference is with the files your script compiles as the node one for example is around 3-4mb and it uses v8 lib which his doesn't. 

I'm relatively new to node and it's requirements so apologies if that's a silly question.

Cheers
Paul

**Comment by nneves** [comment]
@fridaystreet Thanks ;)

Regarding node.js binary size, I haven't gone into much details on the compilation part to understand what could be stripped from node.js to make it slimmer, it took me a looooong time to get this done and credits are not mine, just followed some tips until I got the recipe done:
https://github.com/paul99/v8m-rb/pull/19#issuecomment-23875964

As far as I can remember the initial version compiled by giorgiocefaro was similar to mine (in size), he must have found a way to remove unnecessary stuff out of the way. I haven´t had time to take the extra mile and to be honest I'm fairly happy with the results I got!

I'm interested to take this solution into another SoC embedded system such as the Ralink RT5350 with OpenWrt, maybe can find a way to get the binary more compact.

Glad that this could be useful to you Paul.

Cheers,
Nelson.

**Comment by fridaystreet** [comment]
Hi Nelson,

No worries, thanks for the background info. I only asked because some of the devices I'm playing with have very limited space, but it's not a show stopper, there are other ways around it.

Keep up the good work, apologies in advance as I may bug you a little bit as I try to get a few things working.

Thanks again
Paul
